import Link from "next/link";
import { markets, type Market } from "../catalog";

const marketOrder: Market[] = ["us", "uk", "india", "singapore"];

const pipelineChecks = [
  { label: "Fixture catalog", state: "Ready for demo", tone: "ready", detail: "Market-local fixture rows are labelled and rendered without live freshness claims." },
  { label: "Live collectors", state: "Pending · not configured", tone: "pending", detail: "No production collector IDs are claimed in this build." },
  { label: "Scheduler / trigger", state: "Pending · not configured", tone: "pending", detail: "The downstream trigger is reserved for the Bright Data integration milestone." },
  { label: "Self-heal", state: "Planned · evidence required", tone: "planned", detail: "A repair is only considered real after the same collector is healed, validated, and rerun." },
];

export default function DataHealth() {
  return <main className="site-shell health-page">
    <div className="demo-banner" role="note"><span className="pulse-dot" aria-hidden="true" /><strong>FIXTURE CATALOG</strong><span>Health here describes the current demo state; it does not claim a live scrape or production freshness.</span></div>
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark" aria-hidden="true">R</span><span>raster<span className="brand-dot">.</span></span></Link><nav className="main-nav" aria-label="Primary navigation"><Link href="/#offers">Compare offers</Link><Link href="/how-it-works">How it works</Link><Link href="/data-health" aria-current="page">Data health</Link></nav><span className="status-chip"><span className="status-dot" /> fixture view</span></header>
    <section className="health-hero"><div><p className="eyebrow"><span>05</span> / DATA HEALTH</p><h1>Trust the signal.<br /><em>Know its state.</em></h1><p>One compact view for what is real in the demo, what is still pending, and what the live pipeline must prove before it earns a green badge.</p></div><div className="health-stamp" aria-label="Live collectors not configured"><span className="stamp-ring" aria-hidden="true" /><strong>NO LIVE<br />RUN CLAIMED</strong><small>honesty is a feature</small></div></section>
    <section className="health-section"><div className="section-heading"><div><p className="eyebrow"><span>01</span> / MARKET COVERAGE</p><h2>Four local views.</h2></div><p className="section-note">No FX conversion<br />No cross-market ranking</p></div><div className="market-health-grid">{marketOrder.map((market) => { const info = markets[market]; return <article className="market-health-card" key={market}><div className="health-card-top"><span className="health-icon" aria-hidden="true">{info.symbol}</span><span className="state-pill state-fixture">fixture ready</span></div><h3>{info.label}</h3><p>Market-local offers only</p><strong>{info.currency}</strong><small>Demo rows are clearly labelled. Live collector status: not configured.</small></article>; })}</div></section>
    <section className="health-section pipeline-section"><div className="section-heading"><div><p className="eyebrow"><span>02</span> / PIPELINE READINESS</p><h2>Green means proven.</h2></div><p className="section-note">Pending states stay visible<br />until evidence exists</p></div><div className="pipeline-list">{pipelineChecks.map((check) => <article className="pipeline-row" key={check.label}><span className={`pipeline-mark pipeline-${check.tone}`} aria-hidden="true">{check.tone === "ready" ? "✓" : "·"}</span><div><h3>{check.label}</h3><p>{check.detail}</p></div><strong className={`pipeline-state pipeline-state-${check.tone}`}>{check.state}</strong></article>)}</div></section>
    <section className="health-section evidence-section"><div className="evidence-card"><p className="eyebrow"><span>03</span> / ELIGIBILITY GATE</p><h2>Long tail before live.</h2><p>Before a collector is created, each retailer must pass the public-page and pre-built-coverage checks. This build intentionally shows the gate instead of inventing a collector ID.</p><a className="button button-quiet" href="https://brightdata.com/products/scrapers" target="_blank" rel="noreferrer">Review Bright Data scraper library ↗</a></div><div className="evidence-card"><p className="eyebrow"><span>04</span> / RECOVERY CONTRACT</p><h2>Last-known-good, then quarantine.</h2><p>A failed refresh never silently replaces a known-good row. Keep the last valid snapshot visible with a stale label, quarantine malformed output, describe the failure, and only publish a healed rerun after schema checks pass.</p><div className="recovery-flow" aria-label="Recovery sequence"><span>last good</span><b>→</b><span>quarantine</span><b>→</b><span>heal + validate</span></div></div></section>
    <footer className="site-footer"><Link href="/" className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><span>Fixture health · no live run claimed</span><Link href="/#offers">Back to offers ↗</Link></footer>
  </main>;
}
