import Link from "next/link";
import { loadCatalog } from "../../lib/d1/catalog";

export default async function HowItWorks() {
  const snapshot = await loadCatalog();
  const liveRead = snapshot.source === "postgres";
  return <main className="site-shell method-page">
    <div className="demo-banner" role="note"><span className="pulse-dot" aria-hidden="true" /><strong>{liveRead ? "POSTGRESQL NORMALIZED READ" : "FIXTURE CATALOG"}</strong><span>{liveRead ? "The storefront is reading validated hosted PostgreSQL rows through private Hyperdrive; collector proof remains separately visible in Data Health." : "The offers currently shown are clearly labelled demo fixtures."}</span></div>
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><nav className="main-nav" aria-label="Primary navigation"><Link href="/#offers">Compare offers</Link><Link href="/how-it-works" aria-current="page">How it works</Link><Link href="/data-health">Data health</Link></nav><span className="status-chip"><span className="status-dot" /> {liveRead ? "postgres view" : "fixture view"}</span></header>
    <section className="method-hero"><p className="eyebrow"><span>04</span> / THE METHOD</p><h1>From public page<br /><em>to useful signal.</em></h1><p>Raster is a small, inspectable pipeline. It collects public product pages, normalizes each country into a market-local view, and leaves the buying decision with you.</p></section>
    <section className="method-steps"><article><span className="step-number">01</span><div><h2>Choose or admit a market</h2><p>Four baseline views stay separate. An authenticated Country Pack can add another country at runtime only after its public retailer and custom collector evidence pass the gate.</p><code>country → local currency → admitted source</code></div></article><article><span className="step-number">02</span><div><h2>Collect public pages</h2><p>Bright Data Scraper Studio collectors read approved specialist retailer pages. Shopper input never controls a URL, currency, or Collector ID.</p><code>custom collector → structured rows</code></div></article><article><span className="step-number">03</span><div><h2>Normalize honestly</h2><p>Market, price, availability, source URL, and observation time cross validation before private PostgreSQL. Invalid rows are quarantined; last-known-good data remains visibly degraded.</p><code>validate → normalize → PostgreSQL</code></div></article><article><span className="step-number">04</span><div><h2>Repair with evidence</h2><p>A site change moves through contract break, quarantine, heal preview, approval, same-ID rerun, and validated publish. Raster only marks the proof green after sanitized artifacts exist.</p><code>same c_* → heal → validate → rerun</code></div></article></section>
    <section className="honesty-card"><span className="eyebrow">A NOTE ON CHECKOUT</span><h2>Raster is not the merchant.</h2><p>We never take payment, hold inventory, or promise delivery. “Verify at retailer” opens the original public listing so you can confirm the current details yourself.</p><Link className="button button-quiet" href="/data-health">Inspect evidence state ↗</Link></section>
    <footer className="site-footer"><Link href="/" className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><Link href="/#offers">Back to offers ↗</Link><span>© 2026 Raster</span></footer>
  </main>;
}
