/* eslint-disable jsx-a11y/no-interactive-element-to-noninteractive-role */
import Link from "next/link";
import { formatPrice, getMarket, getModelOffers, markets, models } from "../../catalog";

export function generateStaticParams() { return models.map((model) => ({ slug: model.slug })); }

export default async function GpuDetail({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const { slug } = await params;
  const query = searchParams ? await searchParams : {};
  const market = getMarket(Array.isArray(query.market) ? query.market[0] : query.market);
  const marketInfo = markets[market];
  const modelOffers = getModelOffers(slug, market);
  const model = models.find((item) => item.slug === slug);
  if (!model || modelOffers.length === 0) return <main className="site-shell empty-route"><Link href="/" className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><h1>No {marketInfo.label} fixture for that GPU.</h1><p>Raster does not compare markets together. Return to the market selector to choose another local catalog.</p><Link className="button button-primary" href={`/?market=${market}`}>Back to {marketInfo.label}</Link></main>;
  const lowest = [...modelOffers].sort((a, b) => a.price - b.price)[0];
  return <main className="site-shell detail-page"><div className="demo-banner" role="note"><span className="pulse-dot" aria-hidden="true" /><strong>FIXTURE CATALOG</strong><span>Demo data only · verify every price and stock claim at the retailer.</span></div><header className="topbar"><Link href="/" className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><nav className="main-nav" aria-label="Primary navigation"><Link href={`/?market=${market}#offers`}>Compare offers</Link><Link href="/how-it-works">How it works</Link></nav><span className="status-chip"><span className="status-dot" /> fixture view</span></header><div className="breadcrumbs"><Link href={`/?market=${market}`}>Raster · {marketInfo.label}</Link><span>/</span><span>{model.name}</span></div><section className="detail-hero"><div className="detail-art card-gpu-art"><span>{model.name.split(" ").at(-1)}</span><div /></div><div><p className="eyebrow"><span>MODEL FIXTURE</span> / {modelOffers.length} LOCAL SOURCES</p><h1>{model.name}</h1><p className="detail-spec">{model.vram} · {marketInfo.label} · {marketInfo.currency} comparison</p><div className="detail-price"><span>Lowest fixture in this market</span><strong>{formatPrice(lowest.price, lowest.currency)}</strong><small>{lowest.source} · {lowest.freshness}</small></div></div></section><section className="detail-offers"><div className="section-heading"><div><p className="eyebrow"><span>OFFER LEDGER</span> / MARKET-LOCAL</p><h2>Compare board partners.</h2></div><p className="section-note">No cross-market ranking<br />No currency conversion</p></div><div className="detail-table" role="table" aria-label={`${model.name} ${marketInfo.label} fixtures`}>{modelOffers.map((offer) => <div className="detail-row" role="row" key={offer.id}><div role="cell"><strong>{offer.brand}</strong><span>{offer.source} · {offer.vram}</span></div><div role="cell" className="detail-signal"><span className={`signal signal-${offer.freshnessTone}`}><span /> {offer.availability}</span><small>{offer.freshness}</small></div><strong role="cell" className="detail-row-price">{formatPrice(offer.price, offer.currency)}</strong><a role="cell" href={offer.productUrl} target="_blank" rel="noreferrer">Verify ↗</a></div>)}</div></section><footer className="site-footer"><Link href={`/?market=${market}`} className="brand"><span className="brand-mark">R</span><span>raster<span className="brand-dot">.</span></span></Link><span>Fixture snapshot · verify before purchase</span><Link href="/how-it-works">How it works ↗</Link></footer></main>;
}
